const BOT_UA_PATTERNS = [
  'googlebot',
  'adsbot-google',
  'mediapartners-google',
  'bingbot',
  'slackbot',
  'linkedinbot',
  'whatsapp',
  'yandexbot',
  'duckduckbot',
  'applebot',
  'twitterbot',
  'telegrambot',
  'discordbot',
  'petalbot',
  'ahrefsbot',
  'semrushbot',
  'mj12bot',
  'dotbot',
  'bytespider',
  'baiduspider',
  'seznambot',
  'ia_archiver',
  'slurp',
  'bot/',
  'crawler',
  'spider',
  'facebookexternalhit',
  'bingpreview',
  'curl/',
  'python-requests',
  'wget/',
  'headlesschrome',
  'pingdom',
  'uptimerobot',
  'site24x7',
  'newrelicpinger',
  'statuscake',
]

export function isKnownBot(userAgent: string | null): boolean {
  if (!userAgent) return false
  const ua = userAgent.toLowerCase()
  return BOT_UA_PATTERNS.some((pattern) => ua.includes(pattern))
}
